Repository ThamaraBortolin/SAP007-social-network, pull requests merged in 2022-05, with the labels that each got.

#16 inicio dos testes
  package.json
  src/firebase/__mocks__/exports.js
  src/firebase/auth-firebase.js
  src/firebase/config-firebase.js
  src/firebase/exports.js
  src/index.js
  src/main.js
  src/pages/home/login.js
  src/pages/home/register.js
  test/firebase/auth-firebase.spec.js
  test/index.spec.js
Labels: documentation

#24 Feat/add show posts
  package.json
  src/firebase/firestore.js
  src/pages/home/allPosts.js
  src/pages/home/feed.js
Labels: documentation

#25 Style/estilizando-posts
  src/firebase/firestore.js
  src/index.html
  src/pages/header-and-footer/header-footer.css
  src/pages/home/allPosts.css
  src/pages/home/allPosts.js
  src/pages/home/color.css
  src/pages/home/feed.css
  src/pages/home/feed.js
  src/pages/home/mainHome.css
  src/pages/home/register-login.css
Labels: Feat

#26 Função de editar
  src/firebase/__mocks__/exports.js
  src/firebase/config-firebase.js
  src/firebase/exports.js
  src/firebase/firestore.js
  src/pages/home/allPosts.css
  src/pages/home/allPosts.js
  src/pages/home/feed.js
  src/pages/home/postMobile.js
  test/firebase/auth-firebase.spec.js
Labels: Feat

#27 Feat/add likes perfeito delet concluido
  src/firebase/firestore.js
  src/pages/header-and-footer/header-footer.css
  src/pages/home/allPosts.css
  src/pages/home/allPosts.js
  src/pages/home/feed.css
  src/pages/home/feed.js
  src/pages/home/login.js
  src/pages/home/postMobile.js
Labels: Feat

#28 postagem com foto
  src/firebase/exports.js
  src/firebase/firestore.js
  src/firebase/storage.js
  src/pages/home/allPosts.css
  src/pages/home/allPosts.js
  src/pages/home/feed.css
  src/pages/home/feed.js
Labels: Feat

#29 testes finalizados
  src/firebase/auth-firebase.js
  src/firebase/exports.js
  src/firebase/firestore.js
  src/main.js
  src/pages/header-and-footer/header-footer.css
  src/pages/home/allPosts.css
  src/pages/home/allPosts.js
  src/pages/home/feed.js
  src/pages/home/mainHome.css
  src/pages/home/register-login.css
  src/pages/home/register.js
  test/firebase/auth-firebase.spec.js
Labels: Feat

#30 postagem edição e excluir sem reload
  src/firebase/firestore.js
  src/index.html
  src/pages/home/allPosts.css
  src/pages/home/allPosts.js
  src/pages/home/feed.js
Labels: Feat

#31 post mobile
  src/pages/home/feed.js
  src/pages/home/postMobile.js
Labels: Feat

#32 alterações no css
  src/pages/home/allPosts.css
  src/pages/home/allPosts.js
  src/pages/home/feed.js
  src/pages/home/mainHome.css
  src/pages/home/register-login.css
  src/pages/home/register.js
Labels: CSS

#33 Feat/add css finalizado
  src/images/img/Usuaria.png
  src/pages/header-and-footer/header-footer.css
  src/pages/home/allPosts.css
  src/pages/home/allPosts.js
  src/pages/home/feed.css
  src/pages/home/feed.js
  src/pages/home/postMobile.js
Labels: Feat

#34 Add/read me
  README.md
  package.json
  src/images/img/ProtótipoPop Time-baixa.jpg
  src/images/img/ResultsQ5.png
  src/images/img/descktop-rotasPopTime.png
  src/images/img/fluxogramaLogin (1).png
  src/images/img/formsUser.gif
  src/images/img/mobile-rotas-poptime.jpg
  src/images/img/navegando.gif
Labels: ReadMe

#35 erro cadastrado null
  src/pages/home/register.js
Labels: Feat
